name: sumcoin
description: A new Sumcoin wallet.

version: 0.0.1+1

environment:
  sdk: '>=2.17.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^2.1.0
  crypto: ^3.0.1
  bip39: ^1.0.6
  coinslib: ^3.1.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.6
  provider: ^6.0.3
  share_plus: ^6.2.0
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  step_progress_indicator: ^1.0.0
  qr_code_scanner: ^1.0.0
  url_launcher: ^6.1.4
  flutter_local_notifications: ^13.0.0
  flutter_screen_lock: ^9.0.1
  local_auth: ^2.1.2
  local_auth_android: any
  package_info_plus: ^3.0.1
  mailto: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_typeahead: ^4.0.0
  connectivity_plus: ^3.0.2
  theme_mode_handler: ^3.0.0
  http: ^0.13.3
  collection: ^1.15.0-nullsafety.4
  flutter_markdown: ^0.6.6
  background_fetch: ^1.1.2
  flutter_logs: ^2.1.8
  auto_size_text: ^3.0.0
  camera: ^0.10.0+4
  hex: ^0.2.0
  path_provider: ^2.0.11
  characters: ^1.2.0
  file_picker: ^5.2.2
  fast_csv: ^0.1.44
  protobuf: ^2.1.0
  grpc: ^3.1.0
  mockito: ^5.3.2
  cryptography_flutter: ^2.0.2
  loader_overlay: ^2.1.0
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.5
  firebase_in_app_messaging: ^0.7.3+4
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  cloud_functions: ^4.3.4
  firebase_app_check: ^0.1.5+1
  firebase_auth: ^4.7.0
  firebase_dynamic_links: ^5.3.4
  firebase_app_installations: ^0.2.3+4
  firebase_database: ^10.2.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.7
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/sum-icon.png"
  image_path_ios: "assets/icon/sum-ios-app-xxl.png"
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Sumcoin"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/sum-icon-256.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/translations/
    - assets/img/
    - CHANGELOG.md
